version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/Difficalcy"
      - "/Difficalcy.Catch"
      - "/Difficalcy.Catch.Tests"
      - "/Difficalcy.Mania"
      - "/Difficalcy.Mania.Tests"
      - "/Difficalcy.Osu"
      - "/Difficalcy.Osu.Tests"
      - "/Difficalcy.Taiko"
      - "/Difficalcy.Taiko.Tests"
      - "/Difficalcy.Tests"
    schedule:
      interval: "daily"
    groups:
      test-tools:
        applies-to: version-updates
        patterns:
          - "xunit*"
          - "Microsoft.NET.Test.Sdk"
      osu-rulesets:
        applies-to: version-updates
        patterns:
          - "ppy.osu.Game.Rulesets*"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
