services:
  difficalcy-osu:
    build:
      context: .
      dockerfile: ./Difficalcy.Osu/Dockerfile
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/app/beatmaps
    depends_on:
      - cache

  difficalcy-taiko:
    build:
      context: .
      dockerfile: ./Difficalcy.Taiko/Dockerfile
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/app/beatmaps
    depends_on:
      - cache

  difficalcy-catch:
    build:
      context: .
      dockerfile: ./Difficalcy.Catch/Dockerfile
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/app/beatmaps
    depends_on:
      - cache

  difficalcy-mania:
    build:
      context: .
      dockerfile: ./Difficalcy.Mania/Dockerfile
    environment:
      - REDIS_CONFIGURATION=cache:6379
    volumes:
      - beatmaps:/app/beatmaps
    depends_on:
      - cache

  cache:
    image: redis:6

volumes:
  beatmaps:
