site_name: difficalcy
site_url: https://Syriiin.github.io/difficalcy/
site_description: "A lazer powered osu! difficulty calculation API"
site_author: Samuel Cattini-Schultz
repo_url: https://github.com/Syriiin/difficalcy
repo_name: Syriiin/difficalcy
copyright: |
  &copy; 2024 <a href="https://github.com/Syriiin" target="_blank" rel="noopener">Samuel Cattini-Schultz</a>

nav:
  - index.md
  - getting-started.md
  - api-reference.md

theme:
  name: material
  language: en

  features:
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
